# Generated by Django 5.2.6 on 2025-09-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='abilities', to='rpg.character'),
        ),
    ]
