# Generated by Django 5.2.6 on 2025-09-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_ability_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='characters',
        ),
        migrations.AddField(
            model_name='character',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='rpg.ability'),
        ),
    ]
