# Generated by Django 5.2.6 on 2025-09-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0004_remove_ability_characters_character_abilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('reward', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='type',
            new_name='ability_type',
        ),
    ]
