# Generated by Django 5.2.6 on 2025-09-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_quest_rename_type_ability_ability_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='quests',
            field=models.ManyToManyField(blank=True, to='rpg.quest'),
        ),
    ]
