# Generated by Django 5.2.6 on 2025-09-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_character_quests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot_type', models.CharField(max_length=50)),
                ('characters', models.ManyToManyField(blank=True, related_name='equipment', to='rpg.character')),
            ],
        ),
    ]
